language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: I3fzMxI9j+YDXz8Bzv4zuT6WlNkWAM0rJaSBQFuuI2LgINXyKrevF9opIdXaliNg4AiZvScFvJP1l6MROIq3lUKQeKNk/Cz1CALego3YPGOsHacuEIUz0gHa0WWqrkNFF49x9Hh1FbR8PT1MV5rGo7JU5OQzQZ0++IdKYS9ozq44tJtZ5OghCPWcgfv+RCZjr2GYjTNlTSS3VJJmFfjNdQhbygy9YFb81hGziApbsoq3z1iodR4b92067S3SL5/9Ib6tP7cFYGw/TtuVE8GM4UYoC1+r0+AzOTtFovmJ9K6GkHmAcsGXrWXmHFCvby7oHPLbYqQ7cevx5JGelGwpCe57lrjxeNoIjQujb2ZbF/hcwSmIDZpj7p/yjaz0zVKi1Cz6+Lxxexfe+8E4vYZv4nBw/E5BWbOUectabBn3z14FEfX5Pbh9U6gPknMBtt91JDVmiJNowR9kj+Pvljyb6AxIlgrbk5zaxsZBZl+1wJjhedoEk14idhWi5hfYii5f2wLalKxJ0EzP+hnHug+Q9ilq+ZNMB8ytPv8AoCZovsdjcJWDoQiZGVzz17KKkU1RWMPwTEay6CI7fEchVtRRePsL79uYjJuFz/KemjUAjTz8ASJ+PU00YVKxiNDyWn+r3SWW6y8o98uZcpgyKzzsSRN9K0AjVoPWsPAW1nDiFTE=
  app: immense-refuge-82371
